### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by gav-nomoss** [dashhudson/vue-ld#46]
**TLDR**: We're looking to use vue-ld in a Vue 3 application and it doesn't look like there's support for Vue 3 yet. Is there a timeline on support?

In a Vue 3 app we're configuring `main.js` like this:
```
import { createApp } from 'vue'
import App from './App.vue'
import { VueLd } from 'vue-ld';

const app = createApp(App)
app.use(VueLd, {
    clientSideId: 'YOUR_CLIENT_SIDE_ID',
    user: {
        key: '...',
        email: '...',
        name: '...',
    },
    options: {
        // Standard LaunchDarkly JavaScript SDK options
    },
});
app.mount('#app')
```

When we run the application we're finding that the page doesn't load and we're getting the following error in the console:
```
Uncaught TypeError: Vue.observable is not a function
    at Object.install (index.es.js:1010)
    at Object.use (runtime-core.esm-bundler.js:3003)
    at main.js:6
```

I believe this could be because `Vue.observable` is not supported in Vue 3. Is there a timeline for when vue-ld will support Vue 3? Or, can you point me at a similar tool for Launch Darkly that supports Vue 3?

Thank you!

**Comment by benjamin-t-frost** [comment]
@gav-nomoss we will not be ready to work on upgrading to Vue 3 until fall at least; you are welcome to submit a PR if you need a faster timeline.

**Comment by gav-nomoss** [comment]
Hey @benjamin-t-frost - thanks for getting back. 

We're planning to make use of this library in a Vue 2 project that will eventually be migrated to Vue 3, so it's good to know Vue 3 is on your horizon!
